apiVersion: v1
kind: Service
metadata:
  name: nginx-svc-lb
  labels:
    app: nginx-app
spec:
  type: LoadBalancer
  selector:
    app: nginx-app
  ports:
    - name: http
      port: 80          # public port
      targetPort: 8080  # container port
